### ISSUE TITLE
kbcli can't delete cluster

### ISSUE THREAD

**Issue by xishengcai** [apecloud/kbcli#109]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/apecloud/kbcli/assets/21197150/57dfeece-6cb4-4004-b497-b6cc4589dc6f)

**Desktop (please complete the following information):**
 - kubernetes 1.23.15
 - kbcli  branch main
 
**Additional context**

**Comment by ldming** [comment]
Should check the status of cluster.
