### ISSUE TITLE
[Improvement] add  kubeblocks-addon as submodule of kbcli

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kbcli#128]
KBCLI will build some charts as `embeded-chart` fo fast creation
```bash
.PHONY: build-kbcli-embed-chart
build-kbcli-embed-chart: helmtool fetch-addons create-kbcli-embed-charts-dir \
	build-single-kbcli-embed-chart.apecloud-mysql-cluster \
	build-single-kbcli-embed-chart.redis-cluster \
	build-single-kbcli-embed-chart.postgresql-cluster \
	build-single-kbcli-embed-chart.kafka-cluster \
	build-single-kbcli-embed-chart.mongodb-cluster \
	...
```

That's why KBCLI should fetch the laste version of kubeblocks-addons repo.
we may use GIT `submodule` to manage this repo.

**Comment by 1aal** [comment]
The kbcli now supports adding index repositories, as well as downloading and upgradeing addons from remote sources, which may meet your requirements.

see `kbcli addon index add/delete/update/list` and `kbcli addon search/install/upgrade/uninstall`
