### ISSUE TITLE
[BUG]Auto complete namespace error for dataprotection of alias

### ISSUE THREAD

**Issue by fengluodb** [apecloud/kbcli#188]
dp is the alias for dataprotection cmd, but it can't auto complete namespace.
<img width="1261" alt="image" src="https://github.com/apecloud/kbcli/assets/49025948/eb485b7a-e2ca-42b4-93fc-0d7a19b3accd">
<img width="1143" alt="image" src="https://github.com/apecloud/kbcli/assets/49025948/8ea4de61-2ce4-4176-9229-2345b1dd1ba4">

**Comment by ldming** [comment]
What is the reason? Do other commands have this issue?

**Comment by fengluodb** [comment]
> What is the reason? Do other commands have this issue?

The other commands also have this issue, such as `clusterdefinition` and `clusterversion` command.
<img width="1049" alt="image" src="https://github.com/apecloud/kbcli/assets/49025948/badf1489-d944-44ec-9f68-9258cfc11024">
<img width="820" alt="image" src="https://github.com/apecloud/kbcli/assets/49025948/dd0f799c-fa5b-414d-b0d4-a61402082aec">
<img width="1103" alt="image" src="https://github.com/apecloud/kbcli/assets/49025948/6a6f40f2-448f-4b53-b239-eb700f1e9ea5">
<img width="922" alt="image" src="https://github.com/apecloud/kbcli/assets/49025948/c450baaf-a3f6-48b7-a944-9410124d8758">

**Comment by fengluodb** [comment]
I think the auto completion isn't userful for the command's alis. I don't know the reason now. I think it should the cobra's issue, I will reaserch it.

https://github.com/apecloud/kbcli/blob/f26f982a39693c0ef8ea3192d552fb4f25532e84/pkg/cmd/cli.go#L264-L285
