### ISSUE TITLE
[Improvement] kbcli disable addons in batch

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kbcli#237]
Addons are enabled and disabled ONE at  a time.
e.g. to enabled
```
 kbcli addon enable grafana
```
e.g. to disable

```
 kbcli addon disable grafana
```

It is inconvient sometimes.  
Better to support disable addons in batch with confirmation:
e.g. 
```
kbcli addon disable  grafana prometheus

```

**Comment by SuperAayush** [comment]
Hey @shanshanying, I would like to work on this!!
