### ISSUE TITLE
[BUG] create-account reports  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by weicao** [apecloud/kbcli#255]
**Describe the bug**

weed62 is a polardbx cluster.

$ kbcli cluster create-account weed62 --name test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1022eac68]

goroutine 1 [running]:
github.com/apecloud/kbcli/pkg/cmd/accounts.(*CreateUserOptions).Run(0x1400157e390)
	/home/runner/work/kbcli/kbcli/pkg/cmd/accounts/create.go:82 +0x178
github.com/apecloud/kbcli/pkg/cmd/accounts.(*CreateUserOptions).Exec(0x1400157e390)
	/home/runner/work/kbcli/kbcli/pkg/cmd/accounts/create.go:98 +0x54
github.com/apecloud/kbcli/pkg/cmd/cluster.NewCreateAccountCmd.func1(0x14001565a00?, {0x1400157eed0?, 0x1?, 0x3?})
	/home/runner/work/kbcli/kbcli/pkg/cmd/cluster/accounts.go:98 +0xec
github.com/spf13/cobra.(*Command).execute(0x14001582f00, {0x1400157ee70, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x1400103af00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
k8s.io/component-base/cli.run(0x1400103af00)
	/home/runner/go/pkg/mod/k8s.io/component-base@v0.28.2/cli/run.go:146 +0x264
k8s.io/component-base/cli.RunNoErrOutput(...)
	/home/runner/go/pkg/mod/k8s.io/component-base@v0.28.2/cli/run.go:84
main.main()
	/home/runner/work/kbcli/kbcli/cmd/cli/main.go:31 +0x20

**Comment by weicao** [comment]
KubeBlocks: 0.8.1
kbcli: 0.8.1

**Comment by shanshanying** [comment]
the case when  lorryclient  is nil is not handled properly.
<img width="1044" alt="image" src="https://github.com/apecloud/kbcli/assets/111829739/f4b0cbb5-8604-4423-9813-70e1e5e97896">
