### ISSUE TITLE
[Features] add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by SuperAayush** [apecloud/kbcli#278]
Blocker:
While looking at the GitHub repo it was hard to find how to setup the project on the local machine for development.

DEVELOPING.md file throws 404 error: https://github.com/apecloud/kubeblocks/blob/main/docs/DEVELOPING.md

Fix:
Adding CONTRIBUTING.md files with the proper steps required to set up the project on the local system.

cc - @shanshanying

**Comment by SuperAayush** [comment]
I would like to work on this!!

**Comment by SuperAayush** [comment]
Hello @shanshanying / @ldming would require your assistance to determine the steps for this issue.

Just wanted to ask if we require the running of any specific command to build the project on the local system and then start developing on it. Or just cloning and making direct changes would be enough?

Thanks

**Comment by ldming** [comment]
> Hello @shanshanying / @ldming would require your assistance to determine the steps for this issue.
> 
> Just wanted to ask if we require the running of any specific command to build the project on the local system and then start developing on it. Or just cloning and making direct changes would be enough?
> 
> Thanks

Just clone and change it. Run `make kbcli` to build the kbcli.

**Comment by shanshanying** [comment]
hi @SuperAayush ,
I have sent the instructions in detail through email. please check. And looking forwarding to your next PR on Develop and Contribution Guide.
