### ISSUE TITLE
[BUG]kb configure -h Error in sample code

### ISSUE THREAD

**Issue by dengkailu** [apecloud/kbcli#310]
![img_v3_029o_6a25bfc6-e87c-4047-8e6b-78ccebc1c51g](https://github.com/apecloud/kbcli/assets/165625946/46917096-5cfd-432b-8057-e0cc50f30c25)
`Examples:
  # update component params
  kbcli cluster configure mycluster --component=mysql --config-spec=mysql-3node-tpl --config-file=my.cnf --set
max_connections=1000,general_log=OFF`

**Comment by ldming** [comment]
@dengkailu Would you like to try to fix this issue?
