### ISSUE TITLE
[BUG] "kbcli kb upgrade" fails when interrupted due to network issues.

### ISSUE THREAD

**Issue by hoorayui** [apecloud/kbcli#452]
**Describe the bug**

Interrupted due to a network error when executing the  command `kbcli kb upgrade --version 0.9.1`,
And executed it again, an error is reported.
`kbcli kb upgrade --version 0.9.1`
`error: KubeBlocks does not exist, try to run "kbcli kubeblocks install" to install
`

**To Reproduce**
1. Execute `kbcli kb upgrade --version 0.9.1` and interrupt it .
2. Execute the command again.
3. See error:  **KubeBlocks does not exist, try to run "kbcli kubeblocks install" to install**

**Screenshots**
![企业微信截图_17284437102115](https://github.com/user-attachments/assets/cdbc81be-e9c6-4aec-8534-b2f3b69f27e6)

**Environment (please complete the following information):**
 - Kubernetes: v1.30.2
 - kbcli: 0.9.1
 - Kubeblocks: 0.9.0

**Comment by ldming** [comment]
Now, the upgrade command will delete the deployment, but it will get the KB version from the deployment. So we should get the KB status and version from the helm release.
