### ISSUE TITLE
[Improvement] The example in the help information is incorrect.

### ISSUE THREAD

**Issue by zjial** [apecloud/kbcli#453]
### Is your improvement request related to a problem? Please describe.
The example in the help information for the `kbcli cluster rebuild-instance` command is incorrect. It uses the wrong `instances `option.

### Describe the solution you'd like
Use the `instance `option.

### Additional context
![1728468771526](https://github.com/user-attachments/assets/7a275e13-5eb5-4899-9b74-f727e24ff4fa)

kbcli version:

![1728468847985](https://github.com/user-attachments/assets/0abcda87-400a-406a-a131-11b62a02bb3e)

**Comment by wangyelei** [comment]
fixed
