### ISSUE TITLE
[BUG] `kbcli cluster list -A` command is fail

### ISSUE THREAD

**Issue by 1aal** [apecloud/kbcli#474]
- branch `main`
- run `make kbcli-fast`
- run `./bin/kbcli cluster list -A` with a K8s having KB cluster

![image](https://github.com/user-attachments/assets/bd4ff646-28c8-45a6-a8ff-c224a376277b)
![image](https://github.com/user-attachments/assets/ab33c353-8541-4888-ba0a-9c7c769c71f2)

**Comment by wangyelei** [comment]
kbcli only support 1.0 in main brach

**Comment by wangyelei** [comment]
you can compile a kbcli with branch 0.9
