### ISSUE TITLE
[BUG]kbcli cluster describe failed

### ISSUE THREAD

**Issue by ahjing99** [apecloud/kbcli#54]
➜  ~ kbcli version
Kubernetes: v1.28.3-aliyun.1
KubeBlocks: 0.6.5
kbcli: 0.8.0-alpha.5
WARNING: version difference between kbcli (0.8.0-alpha.5) and kubeblocks (0.6.5)

➜  ~ kbcli cluster describe apecloud-pg -n kubeblocks-cloud
Error from server (NotFound): the server could not find the requested resource

➜  ~ k get cluster apecloud-pg -n kubeblocks-cloud
NAME          CLUSTER-DEFINITION   VERSION             TERMINATION-POLICY   STATUS    AGE
apecloud-pg   postgresql           postgresql-14.8.0   Delete               Running   141m

➜  ~ kbcli cluster list  apecloud-pg -n kubeblocks-cloud
NAME          NAMESPACE          CLUSTER-DEFINITION   VERSION             TERMINATION-POLICY   STATUS    CREATED-TIME
apecloud-pg   kubeblocks-cloud   postgresql           postgresql-14.8.0   Delete               Running   Nov 17,2023 15:26 UTC+0800

**Comment by ldming** [comment]
kbcli 0.8.0 can not describe the 0.6.5 cluster, it's expected that kbcli is not compatible with older versions of the cluster.
